import { GoogleGenAI } from "@google/genai";

const getGeminiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("GEMINI_API_KEY is not set. Gemini API calls will return fallback AI responses.");
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
};

export interface OrchestratorResponse {
  summary: string;
  actions: Array<{
    type: string;
    listTitle?: string;
    card?: {
      title: string;
      description: string;
      entityType: string;
      priority: string;
      tags: string[];
      progress: number;
      widgets: any[];
    };
  }>;
}

export interface SmartSuggestionResponse {
  summary: string;
  suggestedSubtasks: Array<{ id: string; text: string; completed: boolean }>;
  suggestedWidgets: any[];
  suggestedWorkflow: {
    name: string;
    agentRole: string;
    description: string;
    suggestedTags: string[];
  };
}

export interface AgentRunResponse {
  output: string;
  suggestedProgress: number;
  updatedWidgets: any[];
}

export async function callOrchestrator(
  prompt: string,
  currentBoard?: any
): Promise<OrchestratorResponse> {
  const ai = getGeminiClient();

  if (!ai) {
    return {
      summary: `Orchestrator synthesized actions for: "${prompt}"`,
      actions: [
        {
          type: "add_card",
          listTitle: currentBoard?.lists?.[0]?.title || "Product Sync & Feed",
          card: {
            title: `AI Task: ${prompt.slice(0, 30)}...`,
            description: `Generated by KB3.0 Orchestrator based on prompt: "${prompt}"`,
            entityType: prompt.toLowerCase().includes("human") ? "human" : prompt.toLowerCase().includes("swarm") ? "agent_swarm" : "agent",
            priority: "high",
            tags: ["Orchestration", "Auto-Generated"],
            progress: 25,
            widgets: [
              {
                id: `w-auto-${Date.now()}`,
                type: "slider",
                label: "Confidence Score",
                value: 85,
                min: 0,
                max: 100,
                unit: "%"
              },
              {
                id: `w-auto-toggle-${Date.now()}`,
                type: "toggle",
                label: "Auto-Execute Routine",
                value: true
              }
            ]
          }
        }
      ]
    };
  }

  const systemInstruction = `You are the Orchestrator Agent for KB3.0 - The Next-Gen Kanban Board.
Your job is to parse natural language requests and return a JSON structured object detailing what board actions to take.
Available Action Types:
1. 'create_list': Add a new list to the board. Can be 'chat_feed', 'homogenous' (humans_only or agents_only), 'heterogeneous', 'kanban', or 'pipeline'.
2. 'add_card': Add a new card to a specific list with interactive widgets (sliders, toggles, check items, steppers, prompt_runners).
3. 'update_card': Update existing card status or widget values.
4. 'cross_board_feed': Setup or trigger feed-forward routing between lists/boards.

Always return valid JSON matching this schema:
{
  "summary": "Short explanation of actions taken",
  "newLists": [
    {
      "title": "String",
      "listType": "chat_feed" | "homogenous" | "heterogeneous" | "kanban" | "pipeline",
      "homogenousType": "humans_only" | "agents_only" | "none",
      "color": "indigo" | "purple" | "emerald" | "amber" | "rose" | "cyan",
      "cards": [...]
    }
  ],
  "newCards": [
    {
      "targetListTitle": "String",
      "title": "String",
      "description": "String",
      "entityType": "task" | "human" | "agent" | "routine" | "human_team" | "agent_swarm" | "troop",
      "priority": "low" | "medium" | "high" | "urgent",
      "progress": number,
      "tags": ["String"],
      "widgets": [...]
    }
  ]
}`;

  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: `Current Board Context: ${JSON.stringify({
      name: currentBoard?.name,
      lists: currentBoard?.lists?.map((l: any) => ({ title: l.title, type: l.listType, cardCount: l.cards?.length }))
    })}

User Request: "${prompt}"`,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  const responseText = response.text || "{}";
  return JSON.parse(responseText);
}

export async function callTranscribe(audioData: string, mimeType?: string, textQuery?: string): Promise<{ text: string }> {
  if (textQuery) {
    return { text: textQuery };
  }

  if (!audioData) {
    throw new Error("audioData or textQuery is required");
  }

  const ai = getGeminiClient();

  if (!ai) {
    return { text: "Simulated voice transcription: Create a new Agent Swarm for API load testing." };
  }

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: [
      {
        inlineData: {
          mimeType: mimeType || "audio/webm",
          data: audioData,
        },
      },
      {
        text: "Transcribe this spoken audio into concise, clear text instructions for a project task.",
      },
    ],
  });

  return { text: response.text || "Voice transcription processed." };
}

export async function callAgentRun(
  cardTitle: string,
  cardDescription: string,
  prompt?: string,
  widgets?: any[]
): Promise<AgentRunResponse> {
  const ai = getGeminiClient();

  if (!ai) {
    return {
      output: `[Agent Output Simulator] Processed task "${cardTitle}". All routine checks passed with 100% confidence.`,
      suggestedProgress: 100,
      updatedWidgets: widgets?.map((w: any) => {
        if (w.type === "slider") return { ...w, value: Math.min((w.max || 100), (Number(w.value) || 0) + 20) };
        if (w.type === "toggle") return { ...w, value: true };
        if (w.type === "progress_bar") return { ...w, value: 100 };
        return w;
      })
    };
  }

  const promptText = `Card Title: ${cardTitle}
Card Description: ${cardDescription}
Task Prompt: ${prompt || "Execute routine analysis and optimize parameters."}

Please run this task and provide:
1. Executive output summary
2. Updated widget recommendations (progress percentage 0-100)`;

  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: promptText,
    config: {
      systemInstruction: "You are an autonomous AI worker executing a kanban card task. Output a concise execution log.",
    },
  });

  return {
    output: response.text || "Task executed successfully.",
    suggestedProgress: 100,
    updatedWidgets: widgets?.map((w: any) => {
      if (w.type === "slider") return { ...w, value: w.max || 100 };
      if (w.type === "toggle") return { ...w, value: true };
      if (w.type === "progress_bar") return { ...w, value: 100 };
      return w;
    })
  };
}

export async function callSmartSuggestions(
  title: string,
  description?: string,
  entityType?: string,
  priority?: string,
  tags?: string[]
): Promise<SmartSuggestionResponse> {
  const ai = getGeminiClient();

  if (!ai) {
    const subtaskFallback = [
      { id: `s-sugg-1-${Date.now()}`, text: `Define specifications for ${title.slice(0, 25)}`, completed: false },
      { id: `s-sugg-2-${Date.now()}`, text: "Run automated static checks & linting", completed: false },
      { id: `s-sugg-3-${Date.now()}`, text: "Conduct peer review & deployment verification", completed: false }
    ];

    const widgetFallback = [
      { id: `w-sugg-1-${Date.now()}`, type: "slider", label: "Estimated Effort", value: 5, min: 1, max: 10, unit: "pts" },
      { id: `w-sugg-2-${Date.now()}`, type: "toggle", label: "Security Audit Completed", value: false },
      { id: `w-sugg-3-${Date.now()}`, type: "prompt_runner", label: "Auto-Optimize Task", value: `Optimize execution for ${title}` }
    ];

    const workflowFallback = {
      name: "Autonomous Verification & Execution Workflow",
      agentRole: "Lead QA & Security Agent",
      description: "Deploy Gemini agent worker to automatically analyze code diffs, run test coverage, and update status.",
      suggestedTags: ["AI-Driven", "Auto-Verified"]
    };

    return {
      summary: `Smart Suggestion Engine analyzed task "${title}"`,
      suggestedSubtasks: subtaskFallback,
      suggestedWidgets: widgetFallback,
      suggestedWorkflow: workflowFallback
    };
  }

  const systemInstruction = `You are the Smart Suggestion Engine for KB3.0 Kanban Board.
Analyze the user's card title, description, entityType, priority, and tags.
Return a structured JSON object containing:
1. "suggestedSubtasks": array of { "id": string, "text": string, "completed": false } (3 to 5 actionable subtasks)
2. "suggestedWidgets": array of interactive widgets (e.g. slider, toggle, stepper, prompt_runner) relevant to the card
3. "suggestedWorkflow": object with { "name": string, "agentRole": string, "description": string, "suggestedTags": string[] } describing an optimal agent-based workflow to attach.

Always return JSON matching this structure.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: `Card Title: "${title}"
Card Description: "${description || "None provided"}"
Entity Type: "${entityType || "task"}"
Priority: "${priority || "medium"}"
Existing Tags: ${JSON.stringify(tags || [])}`,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  const responseText = response.text || "{}";
  const parsedData = JSON.parse(responseText);

  return {
    summary: parsedData.summary || `Suggestions for "${title}"`,
    suggestedSubtasks: parsedData.suggestedSubtasks || [],
    suggestedWidgets: parsedData.suggestedWidgets || [],
    suggestedWorkflow: parsedData.suggestedWorkflow || null
  };
}
