import { ApiError, GoogleGenAI, Type, type Schema } from "@google/genai";
import { z } from "zod";
import { MODELS } from "../../shared/models.js";
import { AGENT_CAPABILITY_IDS } from "../../shared/agentCapabilities.js";
import {
  OrchestratorResponseSchema,
  describePlanSchemaForPrompt,
  type OrchestratorResponse,
} from "../../shared/contracts/orchestrator.js";
import { PlanProposalSchema, type PlanProposal } from "../../shared/contracts/goalPlan.js";
import type {
  AgentRunApiResponse,
  AgentRunRequest,
  RunErrorCode,
  RunErrorInfo,
} from "../../shared/contracts/agentRun.js";
import type { InteractiveWidget } from "../../types.js";
import { ModelResponseError, parseModelJson } from "./parse.js";

const getGeminiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("GEMINI_API_KEY is not set. Gemini API calls will return fallback AI responses.");
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
};

export type { OrchestratorResponse };

export interface SmartSuggestionResponse {
  summary: string;
  suggestedSubtasks: Array<{ id: string; text: string; completed: boolean }>;
  suggestedWidgets: any[];
  suggestedWorkflow: {
    name: string;
    agentRole: string;
    description: string;
    suggestedTags: string[];
  } | null;
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

function buildOrchestratorFallbackProposal(prompt: string): PlanProposal {
  const trimmedPrompt = prompt.trim();
  const lower = trimmedPrompt.toLowerCase();
  const entityType: "human" | "agent_swarm" | "agent" = lower.includes("human")
    ? "human"
    : lower.includes("swarm")
      ? "agent_swarm"
      : "agent";
  const listTitle =
    trimmedPrompt.length > 0
      ? `Orchestrated: ${trimmedPrompt.slice(0, 40)}${trimmedPrompt.length > 40 ? "…" : ""}`
      : "Orchestrated Tasks";

  return PlanProposalSchema.parse({
    summary: `Orchestrator synthesized a plan for: "${trimmedPrompt}"`,
    newLists: [
      {
        title: listTitle,
        listType: "kanban",
        color: "indigo",
        cards: [
          {
            key: "card-1",
            title: `AI Task: ${trimmedPrompt.slice(0, 30) || "Untitled request"}`,
            description: `Generated by the Orchestrator (fallback mode — no GEMINI_API_KEY configured) based on prompt: "${trimmedPrompt}"`,
            entityType,
            priority: "high",
            tags: ["Orchestration", "Auto-Generated"],
          },
        ],
      },
    ],
    newCards: [],
    suggestedAgents: entityType === "agent_swarm" ? ["code_quality", "testing"] : ["code_quality"],
    notes: ["Fallback response — set GEMINI_API_KEY to enable live orchestration."],
  });
}

export interface OrchestratorCallInput {
  message: string;
  /** Capped context block from the client's buildOrchestratorContext. */
  context?: string;
  /** Last-16-message window of the thread. */
  history?: unknown;
  /** Rolling thread summary. */
  summary?: string;
}

const OrchestratorHistoryEntrySchema = z.object({
  role: z.enum(["user", "assistant"]),
  text: z.string(),
});

function sanitizeHistory(history: unknown): Array<{ role: "user" | "assistant"; text: string }> {
  const parsed = z.array(OrchestratorHistoryEntrySchema).max(16).safeParse(history);
  return parsed.success ? parsed.data : [];
}

export async function callOrchestrator(input: OrchestratorCallInput): Promise<OrchestratorResponse> {
  const ai = getGeminiClient();

  if (!ai) {
    return {
      summary: `Orchestrator synthesized a plan for: "${input.message}"`,
      proposal: buildOrchestratorFallbackProposal(input.message),
    };
  }

  const systemInstruction = `You are the Orchestrator Agent for KayBee - The Next-Gen Kanban Board.
Your job is to parse natural language requests and return a JSON structured object detailing what lists and cards should be created on the board.
Use the workspace context, thread summary, and conversation history below to make the plan specific: prefer adding cards to existing lists when the context shows a good match, reference real agent capabilities for assignedAgentType, and keep new list titles consistent with the board's naming style.

${describePlanSchemaForPrompt()}`;

  const history = sanitizeHistory(input.history);
  const historyBlock =
    history.length > 0
      ? `\n\nRecent conversation:\n${history.map(h => `${h.role}: ${h.text}`).join("\n")}`
      : "";
  const summaryBlock = input.summary ? `\n\nThread summary so far: ${input.summary}` : "";

  const response = await ai.models.generateContent({
    model: MODELS.orchestrator,
    contents: `Workspace Context:\n${input.context || "No workspace context provided."}${summaryBlock}${historyBlock}

User Request: "${input.message}"`,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  return parseModelJson(response.text, OrchestratorResponseSchema, "orchestrate");
}

// ---------------------------------------------------------------------------
// Transcribe
// ---------------------------------------------------------------------------

export async function callTranscribe(audioData: string, mimeType?: string, textQuery?: string): Promise<{ text: string }> {
  if (textQuery) {
    return { text: textQuery };
  }

  if (!audioData) {
    throw new Error("audioData or textQuery is required");
  }

  const ai = getGeminiClient();

  if (!ai) {
    return { text: "Simulated voice transcription: Create a new Agent Swarm for API load testing." };
  }

  const response = await ai.models.generateContent({
    model: MODELS.transcribe,
    contents: [
      {
        inlineData: {
          mimeType: mimeType || "audio/webm",
          data: audioData,
        },
      },
      {
        text: "Transcribe this spoken audio into concise, clear text instructions for a project task.",
      },
    ],
  });

  return { text: response.text || "Voice transcription processed." };
}

// ---------------------------------------------------------------------------
// Agent Run
// ---------------------------------------------------------------------------

const AgentRunModelOutputSchema = z.object({
  output: z.string().default(""),
  progress: z.number().min(0).max(100).nullable().default(null),
  widgetUpdates: z.array(z.object({ id: z.string(), value: z.any() })).default([]),
});

const AGENT_RUN_RESPONSE_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: {
    output: { type: Type.STRING, description: "Execution summary / findings for this run" },
    progress: {
      type: Type.NUMBER,
      nullable: true,
      description: "Your genuine 0-100 progress estimate for the card, or null to leave progress unchanged",
    },
    widgetUpdates: {
      type: Type.ARRAY,
      description: "Updates to apply to specific widgets, referenced by their existing id. Omit widgets you did not change.",
      items: {
        type: Type.OBJECT,
        properties: {
          id: { type: Type.STRING },
          value: {},
        },
        required: ["id", "value"],
      },
    },
  },
  required: ["output"],
};

const RUN_ERROR_RETRYABLE: Record<RunErrorCode, boolean> = {
  invalid_input: false,
  provider_error: true,
  timeout: true,
  rate_limited: true,
  budget_exhausted: false,
  internal: true,
  aborted: false,
};

function makeRunError(code: RunErrorCode, message: string): RunErrorInfo {
  return { code, message, retryable: RUN_ERROR_RETRYABLE[code] };
}

function classifyProviderError(err: unknown): RunErrorInfo {
  if (err instanceof ApiError) {
    if (err.status === 429) {
      return makeRunError("rate_limited", "Gemini API rate limit exceeded.");
    }
    if (err.status === 402) {
      return makeRunError("budget_exhausted", "Gemini API billing/quota exhausted.");
    }
    if (err.status >= 500) {
      return makeRunError("provider_error", `Gemini API server error (${err.status}).`);
    }
    return makeRunError("provider_error", err.message || "Gemini API request failed.");
  }
  return makeRunError("internal", err instanceof Error ? err.message : "Unknown error executing agent run.");
}

function mergeWidgetUpdates(
  original: InteractiveWidget[],
  updates: Array<{ id: string; value: unknown }>
): InteractiveWidget[] {
  if (updates.length === 0) return original;
  const updateMap = new Map(updates.map((u) => [u.id, u.value]));
  return original.map((w) =>
    updateMap.has(w.id) ? { ...w, value: updateMap.get(w.id) as InteractiveWidget["value"] } : w
  );
}

const AGENT_RUN_TIMEOUT_MS = 60_000;

/**
 * In-process idempotency cache for /agent-run, keyed by Idempotency-Key
 * (falls back to runId). Small LRU (~200 entries, 10 minute TTL) so a
 * lease-reclaim retry doesn't re-charge/re-run the same card execution.
 *
 * NOTE: this cache is per-instance/in-memory only. If the server ever runs
 * as more than one process/instance, a retry landing on a different
 * instance will not see the cached result — this needs a shared store
 * (Redis, Firestore, etc.) to be effective at that point.
 */
const IDEMPOTENCY_CACHE_MAX = 200;
const IDEMPOTENCY_TTL_MS = 10 * 60 * 1000;

interface IdempotencyEntry {
  value: AgentRunApiResponse;
  expiresAt: number;
}

const idempotencyCache = new Map<string, IdempotencyEntry>();

function getCachedRun(key: string): AgentRunApiResponse | undefined {
  const entry = idempotencyCache.get(key);
  if (!entry) return undefined;
  if (Date.now() > entry.expiresAt) {
    idempotencyCache.delete(key);
    return undefined;
  }
  // Refresh recency for LRU eviction.
  idempotencyCache.delete(key);
  idempotencyCache.set(key, entry);
  return entry.value;
}

function setCachedRun(key: string, value: AgentRunApiResponse): void {
  if (idempotencyCache.size >= IDEMPOTENCY_CACHE_MAX) {
    const oldestKey = idempotencyCache.keys().next().value;
    if (oldestKey !== undefined) idempotencyCache.delete(oldestKey);
  }
  idempotencyCache.set(key, { value, expiresAt: Date.now() + IDEMPOTENCY_TTL_MS });
}

async function executeAgentRun(request: AgentRunRequest): Promise<AgentRunApiResponse> {
  const ai = getGeminiClient();
  const originalWidgets = (request.widgets ?? []) as InteractiveWidget[];

  if (!ai) {
    return {
      ok: true,
      output: `[Agent Output Simulator] Processed task "${request.cardTitle}". No GEMINI_API_KEY configured — this is a simulated response; progress and widgets are left unchanged.`,
      suggestedProgress: null,
      updatedWidgets: originalWidgets,
      usage: { model: MODELS.agentRun, estimatedTokens: 0 },
    };
  }

  const controller = new AbortController();
  const timeoutHandle = setTimeout(() => controller.abort(), AGENT_RUN_TIMEOUT_MS);

  try {
    const upstreamContext = request.upstream.length
      ? `\n\nUpstream card outputs:\n${request.upstream.map((u) => `- ${u.title} (${u.cardId}): ${u.output}`).join("\n")}`
      : "";
    const goalContext = request.goal
      ? `\n\nParent goal: "${request.goal.title}" — desired outcome: "${request.goal.outcome}"`
      : "";

    const promptText = `Card Title: ${request.cardTitle}
Card Description: ${request.cardDescription}
Task Prompt: ${request.prompt || "Execute routine analysis and optimize parameters."}${upstreamContext}${goalContext}

Current widgets: ${JSON.stringify(originalWidgets)}

Execute this task and report your genuine findings and progress assessment.`;

    const response = await ai.models.generateContent({
      model: request.model || MODELS.agentRun,
      contents: promptText,
      config: {
        systemInstruction:
          request.systemPrompt ||
          "You are an autonomous AI worker executing a kanban card task. Report your honest assessment of progress — do not assume the task is complete.",
        responseMimeType: "application/json",
        responseSchema: AGENT_RUN_RESPONSE_SCHEMA,
        abortSignal: controller.signal,
      },
    });

    let parsed: z.infer<typeof AgentRunModelOutputSchema>;
    try {
      parsed = parseModelJson(response.text, AgentRunModelOutputSchema, "agent-run");
    } catch (err) {
      if (err instanceof ModelResponseError) {
        console.error(`[agent-run] invalid model response: ${err.raw}`);
        return { ok: false, error: makeRunError("provider_error", "Model returned an invalid response.") };
      }
      throw err;
    }

    return {
      ok: true,
      output: parsed.output || "Task executed successfully.",
      suggestedProgress: parsed.progress,
      updatedWidgets: mergeWidgetUpdates(originalWidgets, parsed.widgetUpdates),
      usage: {
        model: request.model || MODELS.agentRun,
        estimatedTokens: response.usageMetadata?.totalTokenCount ?? 0,
      },
    };
  } catch (err) {
    if (controller.signal.aborted) {
      return { ok: false, error: makeRunError("timeout", `Agent run exceeded the ${AGENT_RUN_TIMEOUT_MS / 1000}s execution budget.`) };
    }
    return { ok: false, error: classifyProviderError(err) };
  } finally {
    clearTimeout(timeoutHandle);
  }
}

export async function callAgentRun(request: AgentRunRequest, idempotencyKey: string): Promise<AgentRunApiResponse> {
  const cached = getCachedRun(idempotencyKey);
  if (cached) return cached;

  const result = await executeAgentRun(request);
  setCachedRun(idempotencyKey, result);
  return result;
}

// ---------------------------------------------------------------------------
// Smart Suggestions
// ---------------------------------------------------------------------------

const SmartSuggestionModelSchema = z.object({
  summary: z.string().default(""),
  suggestedSubtasks: z
    .array(z.object({ id: z.string(), text: z.string(), completed: z.boolean().default(false) }))
    .default([]),
  suggestedWidgets: z.array(z.any()).default([]),
  suggestedWorkflow: z
    .object({
      name: z.string(),
      agentRole: z.string(),
      description: z.string(),
      suggestedTags: z.array(z.string()).default([]),
    })
    .nullable()
    .default(null),
});

export async function callSmartSuggestions(
  title: string,
  description?: string,
  entityType?: string,
  priority?: string,
  tags?: string[]
): Promise<SmartSuggestionResponse> {
  const ai = getGeminiClient();

  if (!ai) {
    const subtaskFallback = [
      { id: `s-sugg-1-${Date.now()}`, text: `Define specifications for ${title.slice(0, 25)}`, completed: false },
      { id: `s-sugg-2-${Date.now()}`, text: "Run automated static checks & linting", completed: false },
      { id: `s-sugg-3-${Date.now()}`, text: "Conduct peer review & deployment verification", completed: false },
    ];

    const widgetFallback = [
      { id: `w-sugg-1-${Date.now()}`, type: "slider", label: "Estimated Effort", value: 5, min: 1, max: 10, unit: "pts" },
      { id: `w-sugg-2-${Date.now()}`, type: "toggle", label: "Security Audit Completed", value: false },
      { id: `w-sugg-3-${Date.now()}`, type: "prompt_runner", label: "Auto-Optimize Task", value: `Optimize execution for ${title}` },
    ];

    const workflowFallback = {
      name: "Autonomous Verification & Execution Workflow",
      agentRole: "Lead QA & Security Agent",
      description: "Deploy Gemini agent worker to automatically analyze code diffs, run test coverage, and update status.",
      suggestedTags: ["AI-Driven", "Auto-Verified"],
    };

    return {
      summary: `Smart Suggestion Engine analyzed task "${title}"`,
      suggestedSubtasks: subtaskFallback,
      suggestedWidgets: widgetFallback,
      suggestedWorkflow: workflowFallback,
    };
  }

  const systemInstruction = `You are the Smart Suggestion Engine for KayBee Kanban Board.
Analyze the user's card title, description, entityType, priority, and tags.
Return a structured JSON object containing:
1. "suggestedSubtasks": array of { "id": string, "text": string, "completed": false } (3 to 5 actionable subtasks)
2. "suggestedWidgets": array of interactive widgets (e.g. slider, toggle, stepper, prompt_runner) relevant to the card
3. "suggestedWorkflow": object with { "name": string, "agentRole": string, "description": string, "suggestedTags": string[] } describing an optimal agent-based workflow to attach.

Always return JSON matching this structure.`;

  const response = await ai.models.generateContent({
    model: MODELS.smartSuggestions,
    contents: `Card Title: "${title}"
Card Description: "${description || "None provided"}"
Entity Type: "${entityType || "task"}"
Priority: "${priority || "medium"}"
Existing Tags: ${JSON.stringify(tags || [])}`,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  const parsed = parseModelJson(response.text, SmartSuggestionModelSchema, "smart-suggestions");

  return {
    summary: parsed.summary || `Suggestions for "${title}"`,
    suggestedSubtasks: parsed.suggestedSubtasks,
    suggestedWidgets: parsed.suggestedWidgets,
    suggestedWorkflow: parsed.suggestedWorkflow,
  };
}

// ---------------------------------------------------------------------------
// Goal Decomposition
// ---------------------------------------------------------------------------

function buildGoalDecompositionFallback(goal: { title: string; description: string; outcome: string }): PlanProposal {
  return PlanProposalSchema.parse({
    summary: `Decomposed goal "${goal.title}" into actionable lists and tasks`,
    newLists: [
      {
        title: "Planning & Research",
        listType: "kanban",
        color: "indigo",
        cards: [
          {
            title: `Research: ${goal.title}`,
            description: "Gather requirements and research best practices",
            entityType: "task",
            priority: "high",
            tags: ["Planning", "Research"],
          },
        ],
      },
      {
        title: "Development",
        listType: "kanban",
        color: "emerald",
        cards: [
          {
            title: `Implement: ${goal.title}`,
            description: "Core development work",
            entityType: "agent",
            priority: "high",
            tags: ["Development", "Auto-Assigned"],
            assignedAgentType: "code_quality",
          },
        ],
      },
      {
        title: "Testing & QA",
        listType: "kanban",
        color: "amber",
        cards: [
          {
            title: `Test: ${goal.title}`,
            description: "Automated and manual testing",
            entityType: "agent",
            priority: "medium",
            tags: ["QA", "Testing"],
            assignedAgentType: "testing",
          },
        ],
      },
    ],
    newCards: [],
    suggestedAgents: ["code_quality", "testing", "documentation"],
    notes: [],
  });
}

/**
 * Returns a PlanProposal-compatible shape (flat `{summary, newLists, newCards,
 * suggestedAgents, notes}`) so both this and the orchestrator's `proposal`
 * feed the same client-side normalizer (`materializePlan`).
 */
export async function callGoalDecomposition(
  goal: { title: string; description: string; outcome: string },
  currentBoard?: any
): Promise<PlanProposal> {
  const ai = getGeminiClient();

  if (!ai) {
    return buildGoalDecompositionFallback(goal);
  }

  const capabilities = AGENT_CAPABILITY_IDS.join(" | ");

  const systemInstruction = `You are the Goal Decomposition Agent for KayBee Kanban Board.
Your job is to break down high-level user goals into actionable lists and tasks that can be autonomously executed by AI agents.

Given a goal with title, description, and desired outcome, return a structured JSON object matching this schema:
{
  "summary": "Brief explanation of the decomposition strategy",
  "newLists": [
    {
      "title": "string",
      "listType": "kanban",
      "color": "string (e.g. indigo, purple, emerald, amber, rose, cyan)",
      "cards": [
        {
          "title": "Action-oriented task name",
          "description": "What needs to be done",
          "entityType": "task" | "human" | "agent",
          "priority": "low" | "medium" | "high" | "urgent",
          "tags": ["string"],
          "assignedAgentType": "(optional) one of: ${capabilities}"
        }
      ]
    }
  ],
  "newCards": [],
  "suggestedAgents": [${capabilities}],
  "notes": []
}

Return 3-5 lists representing workflow stages (e.g., Planning, Development, Testing, Deployment), each with 2-4 cards.
Always return valid JSON matching this schema.`;

  const response = await ai.models.generateContent({
    model: MODELS.goalDecompose,
    contents: `Goal Title: "${goal.title}"
Goal Description: "${goal.description}"
Desired Outcome: "${goal.outcome}"

Current Board Context: ${currentBoard ? JSON.stringify({ name: currentBoard.name, existingLists: currentBoard.lists?.length }) : "No board context"}`,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  return parseModelJson(response.text, PlanProposalSchema, "goal-decompose");
}
